---
version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=666
      - PGID=666
      - TZ=America/New_York
      - UMASK=002
    volumes:
      - /local-mirror1/docker/bazarr/:/config
      - /mnt/storage/shared/Media:/Media
#    ports:
#      - 6767:6767
    restart: unless-stopped
networks:
  default:
    name: MediaBackend
    external: true
