---
version: "2.1"
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=666
      - PGID=666
      - TZ=America/New_York
    volumes:
      - /local-mirror1/docker/readarr:/config
      - /mnt/storage/shared/Media:/Media
#    ports:
#      - 8787:8787
    restart: unless-stopped
networks:
  default:
    name: MediaBackend
    external: true
