---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=666
      - PGID=666
      - TZ=America/New_York
    volumes:
      - /local-mirror1/docker/sonarr:/config
      - /mnt/storage/shared/Media:/Media
#    ports:
#      - 8989:8989
    restart: unless-stopped
networks:
  default:
    name: MediaBackend
    external: true
